

START:                       
                
    ; CARRY FLAG MAY BE SET MANUALLY WITH INSTRUCTIONS BELOW
                              
    STC; SET CARRY FLAG FROM 0 -> 1
    CLC; CLEAR CARRY FLAG FROM 1 -> 0
    CMC; INVERT CARRY FLAG 0 -> 1
    CMC; INVERT CARRY FLAG 1 -> 0
      
    
    ;CARRY FLAG MAY ALSO BE SET WHEN AN ARITHMETIC OPERATION
    ;RESULTS IN A CARRY OUT OR OVERFLIW   
    
    MOV AX, 0FFFFH; FILL AX REGISTER WITH MAXIMUM CAPACITY
    ADD AX, 00001H; ADD 1 CAUSING OVER FLOW
    
    HLT; HALF 8086 PROCESSOR
    
